name: release
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: release
        run: echo "release"
        env:
          PROD_TOKEN: ${{ secrets.PROD_TOKEN }}
